/**
 * \file system.h
 */

#ifndef SYSTEM_H
#define SYSTEM_H

/**
 * This constant determines the number of \a Cells in the universe.
 */
const int ISIZE = 6;

/**
 * The number of neighbours of a cell, including itself.
 */
const int NUM_CELL_NEIGHBOURS = 27;

/**
 * This constant determines the number of genes in \a Prey \a Genome.
 */
const int PREY_GENE_SIZE = 17;

/**
 * This constant determines the number of genes from the entire \a Genome 
 * of \a Prey used for generating patterns.
 */
const int PATTERN_GENE_SIZE = 8;

/**
 * This constant determines the size of pattern generated by Cellular Automata.
 */
const int PATTERN_SIZE = 16;

/**
 * This constant determines the number of genes in \a Predator \a Genome.
 */
const int PREDATOR_GENE_SIZE = 5;

/**
 * Class \a System is used only to store the values of
 * various constants and counters
 * so that they do not pollute the global name space.
 */
class System
{
public:
	static const double WORLD_SIZE;
	static const double HALF_WORLD_SIZE;
	static const double CELL_SIZE;
	static const int	TOTAL_NUMBER_OF_CELLS;
	static const double FORCE_FACTOR;
	static const double DT;
	static const double FRICTION;
	static const double WORK_FACTOR;

	/**
	 * \a Prey properties
	 */
	static int			PREY_SIZE;
	static const int	PREY_REPRODUCTION_AGE_LIMIT;
	static const int	PREY_REPRODUCTION_INTERVAL;
	static const int	PREY_DEMISE_AGE;
	static const float	PATTERN_MUTATION_RATE;
	static const float	PREY_GENOME_MUTATION_RATE;

	/**
	 * \a Mimicry ring properties
	 */
	static const int	MIMICRY_RING_HAMMING_DIST;

	/**
	 * \a Predator properties
	 */
	static const int	MIN_MEMORY_SIZE;
	static const int	MAX_MEMORY_SIZE;
	static const int	HOPFIELD_MAX_ITERATION;
	static const int	PREDATOR_ATTACK_AGE;
	static const int	PREDATOR_ATTACK_INTERVAL;
	static const float	PREDATOR_GENOME_MUTATION_RATE;
	static const int	PREDATOR_DEMISE_AGE;
	static const int	PREDATOR_REPRODUCTION_AGE_LIMIT;
	static const int	PREDATOR_REPRODUCTION_INTERVAL;

	static int showOutline;
	static int showCells;
};

#endif
